language: scala
scala:
# When updating Scala versions, also check the excludes
# in build matrix below.
- 2.12.7
jdk:
- oraclejdk8
- openjdk11
env:
  matrix:
    - SCRIPT=scripts/test-sbt
    - SCRIPT=scripts/test-gradle
script:
- $SCRIPT
cache:
  directories:
  - "$HOME/.ivy2/cache"
  - "$HOME/.gradle/caches"
before_cache:
- rm -rf $HOME/.ivy2/cache/com.typesafe.play/*
- rm -rf $HOME/.ivy2/cache/scala_*/sbt_*/com.typesafe.play/*
- find $HOME/.ivy2/cache -name "ivydata-*.properties" -print0 | xargs -n10 -0 rm

# Exclude some combinations from build matrix. See:
# https://docs.travis-ci.com/user/customizing-the-build/#Build-Matrix
matrix:
  fast_finish: true
  allow_failures:
    # Current release of Gradle still does not supports Play 2.7.x releases
    # As soon as there is a release of Gradle that fixes that, we can then
    # remove this allowed failure.
    - env: SCRIPT=scripts/test-gradle
    # We are not fully validating for Java 11 yet, so we allow this to
    # failure until we tackle all the problems. Anyway, having it at the
    # build helps us to track the progress and discover problems sooner.
    - jdk: openjdk11
    
# See https://blog.travis-ci.com/2014-03-13-slack-notifications/
# created with travis encrypt command line tool
notifications:
  slack:
    secure: K6HWTI6zJpQfxS7sH5ZQ1jEK5TkkUl5GtcGinNecHMBqvfS4IXAnU23lz/kLqCqMVPIFaRx1g6UwgJgMvR4XWeIhpzLOzAnOOcmv+kQzv7A8vEJBM20z1HNzDcxzvuNNO2BHn8EjXh5VD65vXMcA+lKzUxASey/Rs+CBReQWE7M=
