language: scala
dist: trusty
sudo: true
group: beta
scala:
- 2.11.8
jdk:
- oraclejdk8
script:
- "./scripts/gencerts.sh"
- "./play test"
cache:
  directories:
  - "$HOME/.ivy2/cache"
  - "$HOME/.sbt/boot/"
  - "$HOME/.sbt/launchers/"
before_cache:
- rm -rf $HOME/.ivy2/cache/com.typesafe.play/*
- rm -rf $HOME/.ivy2/cache/scala_*/sbt_*/com.typesafe.play/*
- find $HOME/.ivy2/cache -name "ivydata-*.properties" -print0 | xargs -n10 -0 rm
notifications:
  slack:
    secure: HgykeJkGaEm2Z4FJhZaqJwaO55ZHyTP5HBLepOV803U0TOb3ZeHmYb+Q4r1iwgRYxlnX14dP+tbAQ7AfD0vhXUMOwKeevQF/NFLhC6TYAXJuSOm5ZDLtGetGJabrZQo/Fqeidr/OW5NjC2e3/HyfhNuFXUgCYrjqif4FMEp314k=
